# Generated by Django 3.1.5 on 2021-01-27 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=5)),
                ('state', models.CharField(choices=[('ND', 'No data'), ('GO', 'Good'), ('ME', 'Medium'), ('BA', 'Bad')], default='ND', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('revenue', models.IntegerField()),
                ('revenueP', models.FloatField(default=0)),
                ('eps', models.FloatField()),
                ('epsP', models.FloatField(default=0)),
                ('equity', models.IntegerField(default=0)),
                ('equityP', models.FloatField(default=0)),
                ('PE', models.FloatField(default=0)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figure', to='stock.stock')),
            ],
        ),
    ]
