# Generated by Django 3.1.5 on 2021-01-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20210127_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='stock',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='stock',
            field=models.ManyToManyField(to='stock.Stock'),
        ),
    ]
