# Generated by Django 3.1.5 on 2021-01-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('method', models.CharField(choices=[('B', 'Bank'), ('C', 'Cash'), ('S', 'Stock')], default='C', max_length=1)),
            ],
        ),
    ]
