# Generated by Django 3.1.5 on 2021-02-01 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(default=0)),
                ('total_earn', models.IntegerField(default=0)),
                ('total_spend', models.IntegerField(default=0)),
                ('score', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('value', models.IntegerField(default=0)),
                ('score', models.FloatField(default=0)),
                ('total_earn', models.IntegerField(default=0)),
                ('total_spend', models.IntegerField(default=0)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month', to='finance.year')),
            ],
        ),
    ]
