# Generated by Django 3.1.5 on 2021-02-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_month_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='cash',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='month',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='year',
            name='cash',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='year',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
