# Generated by Django 3.1.5 on 2021-02-02 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20210201_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='month',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='finance.month'),
            preserve_default=False,
        ),
    ]
