# Generated by Django 3.1.5 on 2021-02-13 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_remove_transaction_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='crypto',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='year',
            name='crypto',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='finance.month'),
        ),
    ]
