# Generated by Django 3.1.5 on 2021-02-17 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_transaction_tfrom'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tto',
            field=models.CharField(blank=True, choices=[('ST', 'Stock'), ('SP', 'Spending'), ('EA', 'Earning'), ('CA', 'Cash'), ('CR', 'Crypto')], max_length=2, null=True),
        ),
    ]
