# Generated by Django 3.1.5 on 2021-02-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_transaction_tto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tfrom',
            field=models.CharField(blank=True, choices=[('ST', 'Stock'), ('SP', 'Spending'), ('EA', 'Earning'), ('CA', 'Cash'), ('CR', 'Crypto'), ('VO', 'Void')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tto',
            field=models.CharField(blank=True, choices=[('ST', 'Stock'), ('SP', 'Spending'), ('EA', 'Earning'), ('CA', 'Cash'), ('CR', 'Crypto'), ('VO', 'Void')], max_length=2, null=True),
        ),
    ]
