# Generated by Django 3.1.5 on 2021-02-25 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_auto_20210224_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='tfrom',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='tto',
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=256)),
                ('amount', models.IntegerField()),
                ('tfrom', models.CharField(blank=True, choices=[('Stock', 'Stock'), ('Spending', 'Spending'), ('Earning', 'Earning'), ('Cash', 'Cash'), ('Crypto', 'Crypto'), ('Avail', 'Avail')], max_length=8, null=True)),
                ('tto', models.CharField(blank=True, choices=[('Stock', 'Stock'), ('Spending', 'Spending'), ('Earning', 'Earning'), ('Cash', 'Cash'), ('Crypto', 'Crypto'), ('Avail', 'Avail')], max_length=8, null=True)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer', to='finance.month')),
            ],
        ),
    ]
