# Generated by Django 3.1.5 on 2021-02-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_auto_20210225_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='action',
            field=models.CharField(blank=True, choices=[('Plus', 'Plus'), ('Minus', 'Minus')], max_length=5, null=True),
        ),
    ]
