# Generated by Django 3.1.5 on 2021-02-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_transaction_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='crypto',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='year',
            name='crypto',
            field=models.IntegerField(default=0),
        ),
    ]
