# Generated by Django 3.1.5 on 2021-01-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figure',
            name='year',
            field=models.IntegerField(),
        ),
    ]
