# Generated by Django 3.1.5 on 2021-01-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20210119_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='figure',
            name='epsP',
            field=models.FloatField(default=-999),
        ),
        migrations.AddField(
            model_name='figure',
            name='revenueP',
            field=models.FloatField(default=-999),
        ),
    ]
