# Generated by Django 3.1.5 on 2021-01-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_auto_20210119_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figure',
            name='eps',
            field=models.FloatField(),
        ),
    ]
