# Generated by Django 3.1.5 on 2021-01-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_auto_20210120_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='state',
            field=models.CharField(choices=[('ND', 'No data'), ('GO', 'Good'), ('ME', 'Medium'), ('BA', 'Bad')], default='ND', max_length=2),
        ),
    ]
