# Generated by Django 3.1.5 on 2021-01-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_stock_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='figure',
            name='PE',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='figure',
            name='equity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='figure',
            name='equityP',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='figure',
            name='epsP',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='figure',
            name='revenueP',
            field=models.FloatField(default=0),
        ),
    ]
