# Generated by Django 3.1.5 on 2021-01-20 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0008_auto_20210120_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.myday')),
            ],
        ),
    ]
