# Generated by Django 3.1.5 on 2021-01-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0009_daytask'),
    ]

    operations = [
        migrations.AddField(
            model_name='daytask',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
