# Generated by Django 3.1.5 on 2021-01-21 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0010_daytask_finished'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='daytask',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dayTask', to='personal.myday'),
        ),
    ]
