# Generated by Django 3.1.5 on 2021-01-21 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0011_auto_20210121_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='myday',
            name='week',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='myday', to='personal.myweek'),
            preserve_default=False,
        ),
    ]
