# Generated by Django 3.1.5 on 2021-01-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0017_auto_20210122_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='myweek',
            name='total_finished_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myweek',
            name='total_weight',
            field=models.IntegerField(default=0),
        ),
    ]
