# Generated by Django 3.1.5 on 2021-01-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0023_auto_20210122_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_money', models.IntegerField(default=0)),
            ],
        ),
    ]
