# Generated by Django 3.1.5 on 2021-01-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0025_auto_20210122_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskgroup',
            name='sort_value',
            field=models.IntegerField(default=0),
        ),
    ]
