# Generated by Django 3.1.5 on 2021-01-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0028_task_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='daily_money',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='task_weight_money',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='weekly_money',
            field=models.IntegerField(default=0),
        ),
    ]
