# Generated by Django 3.1.5 on 2021-01-24 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0029_auto_20210124_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='day_score_weight',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='thresh_hold',
            field=models.IntegerField(default=0),
        ),
    ]
