# Generated by Django 3.1.5 on 2021-01-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0031_month_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='month',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
