# Generated by Django 3.1.5 on 2021-01-24 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0033_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
