# Generated by Django 3.1.5 on 2021-01-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0036_myday_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskgroup',
            name='money_per_weight',
            field=models.FloatField(default=0),
        ),
    ]
