# Generated by Django 3.1.5 on 2021-02-01 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0037_taskgroup_money_per_weight'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Month',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
