# Generated by Django 3.1.5 on 2021-02-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0038_auto_20210201_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myday',
            old_name='quote',
            new_name='noneed',
        ),
        migrations.AddField(
            model_name='quote',
            name='author',
            field=models.CharField(default='Undefined', max_length=256),
        ),
        migrations.AlterField(
            model_name='quote',
            name='name',
            field=models.TextField(),
        ),
    ]
