# Generated by Django 3.1.5 on 2021-03-05 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0040_myday_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoCreatedTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('finished', models.BooleanField(default=False)),
                ('weight', models.IntegerField(default=0)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_create_task', to='personal.myday')),
            ],
        ),
    ]
