# Generated by Django 3.1.5 on 2021-03-05 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0041_autocreatedtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autocreatedtask',
            name='day',
        ),
    ]
