# Generated by Django 3.1.5 on 2021-03-05 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0043_remove_autocreatedtask_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskgroup',
            name='money_per_weight',
        ),
        migrations.RemoveField(
            model_name='taskgroup',
            name='reward_weight',
        ),
    ]
